/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.daggerok

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertNotNull("not null")
    }
}
